"""followers

Revision ID: 2a3a2259b9dc
Revises: 6286f3870d60
Create Date: 2023-10-13 23:58:20.707098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3a2259b9dc'
down_revision = '6286f3870d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_post_timestap')
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('timestap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestap', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.create_index('ix_post_timestap', ['timestap'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
